/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.restaurant.mx.desktop.app.view;

import org.restaurant.mx.controladores.ControladorCategoriaPlatillo;
import org.restaurant.mx.controladores.ControladorPlatillo;
import org.restaurant.mx.modelo.CategoriaExt;
import org.restaurant.mx.modelo.CategoriaPlatillo;
import org.restaurant.mx.modelo.Platillo;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author JAST
 */
public class JPlatilloSeleccion extends javax.swing.JPanel {

    public DefaultListModel modeloPlatillos;
    public DefaultComboBoxModel modeloCategorias;
    private ControladorCategoriaPlatillo conCat;
    private ControladorPlatillo conPla;
    
    /**
     * Creates new form JPlatilloSeleccion
     */
    public JPlatilloSeleccion() {
        initComponents();
        modeloPlatillos = new DefaultListModel();
        modeloCategorias = new DefaultComboBoxModel();
        conCat = new ControladorCategoriaPlatillo();
        conPla = new ControladorPlatillo();
        cargarCategorias();
        listarTodos();
    }

    public void cargarCategorias() {
        List<CategoriaPlatillo> cats = conCat.listar();
        modeloCategorias.addElement(null);
        for(CategoriaPlatillo cp : cats) {
            CategoriaExt ce = new CategoriaExt();
            ce.setCategoriaPlatillo(cp);
            modeloCategorias.addElement(ce);
        }
        cboCategoria.setModel(modeloCategorias);
    }
    
    public void listarTodos() {
        modeloPlatillos = new DefaultListModel();
        List<Platillo> lista = conPla.listar();
        for(Platillo p : lista) {
            modeloPlatillos.addElement(p);
        }
        lstPlatillos.setModel(modeloPlatillos);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        cboCategoria = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPlatillos = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        spnCantidad = new javax.swing.JSpinner();

        jTextField1.setText("jTextField1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Categoria:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nombre:");

        jtfNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNombreKeyReleased(evt);
            }
        });

        cboCategoria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCategoriaActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstPlatillos);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Cantidad:");

        spnCantidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        spnCantidad.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cboCategoria, 0, 176, Short.MAX_VALUE)
                                .addComponent(jtfNombre)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCategoriaActionPerformed
        if((cboCategoria.getSelectedIndex() == -1 || cboCategoria.getSelectedIndex() == 0) && jtfNombre.getText().equals("")) {
            listarTodos();
        } else if((cboCategoria.getSelectedIndex() == -1 || cboCategoria.getSelectedIndex() == 0) && !jtfNombre.getText().equals("")){
            List<Platillo> plats = conPla.listarPorFiltro(null, jtfNombre.getText());
            if(plats != null) {
            modeloPlatillos = new DefaultListModel();
                for(Platillo p : plats) {
                    modeloPlatillos.addElement(p);
                }
                lstPlatillos.setModel(modeloPlatillos);
            } else {
                lstPlatillos.setModel(new DefaultListModel());
            }
        } else {
            CategoriaPlatillo catp = (CategoriaPlatillo) cboCategoria.getSelectedItem();
            List<Platillo> plats = conPla.listarPorFiltro(catp.getIdCategoria(), jtfNombre.getText());
            if(plats != null) {
            modeloPlatillos = new DefaultListModel();
                for(Platillo p : plats) {
                    modeloPlatillos.addElement(p);
                }
                lstPlatillos.setModel(modeloPlatillos);
            } else {
                lstPlatillos.setModel(new DefaultListModel());
            }
        }
    }//GEN-LAST:event_cboCategoriaActionPerformed

    private void jtfNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreKeyReleased
        if((cboCategoria.getSelectedIndex() == -1 || cboCategoria.getSelectedIndex() == 0) && jtfNombre.getText().equals("")) {
            listarTodos();
        } else if((cboCategoria.getSelectedIndex() == -1 || cboCategoria.getSelectedIndex() == 0) && !jtfNombre.getText().equals("")){
            List<Platillo> plats = conPla.listarPorFiltro(null, jtfNombre.getText());
            if(plats != null) {
            modeloPlatillos = new DefaultListModel();
                for(Platillo p : plats) {
                    modeloPlatillos.addElement(p);
                }
                lstPlatillos.setModel(modeloPlatillos);
            } else {
                lstPlatillos.setModel(new DefaultListModel());
            }
        } else {
            CategoriaPlatillo catp = (CategoriaPlatillo) cboCategoria.getSelectedItem();
            List<Platillo> plats = conPla.listarPorFiltro(catp.getIdCategoria(), jtfNombre.getText());
            if(plats != null) {
            modeloPlatillos = new DefaultListModel();
                for(Platillo p : plats) {
                    modeloPlatillos.addElement(p);
                }
                lstPlatillos.setModel(modeloPlatillos);
            } else {
                lstPlatillos.setModel(new DefaultListModel());
            }
        }
    }//GEN-LAST:event_jtfNombreKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox cboCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jtfNombre;
    public javax.swing.JList lstPlatillos;
    public javax.swing.JSpinner spnCantidad;
    // End of variables declaration//GEN-END:variables
}
